version: '3.3'

services:
    web:
        image: mesa/alpine-nginx-php7:${CONTAINER_VERSION}
        build: ./
        container_name: mesa-nginx
        ports:
            - "80:80"
networks:
    default:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"